language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "6"
dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: "latest-esr"
before_install:
  - if [[ -n "${AAT_TOKEN}" ]]; then sed -e "s|\${AAT_TOKEN}|$AAT_TOKEN|g" < .aat.yml.src > .aat.yml; fi
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm prune
  - npm install || (cat npm-debug.log; false)
  - npm i https://aat.mybluemix.net/dist/karma-ibma.tgz

script:
  - npm run lint
  - npm run build
  - npm run test:unit -- -b PhantomJS -b Chrome -b Firefox
  - if [[ -n "${SAUCE_ACCESS_KEY}" ]]; then npm run test:unit -- -s -d -b Chrome -b Firefox -b Safari -b MicrosoftEdge -b IE; fi
  - if [[ -n "${AAT_TOKEN}" ]]; then (npm run test:a11y || true); fi
  - find tests/spec -name "*.js" ! -name left-nav_spec.js -print0 | xargs -0 -n 1 -P 1 npm run test:unit -- -d -f
