language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "4"
  - "6"

addons:
  firefox: "latest-esr"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@~3.8.0; npm cache clean; fi
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install || (cat npm-debug.log; false)

script:
  - npm run build
  - npm test -- -b PhantomJS -b Chrome -b Firefox
  - find tests/spec -name "*.js" ! -name left-nav_spec.js -print0 | xargs -0 -n 1 -P 1 npm test -- -d -f
  - npm run lint
