version: 2
jobs:
  system:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
            # Reference:
            # https://circleci.com/docs/2.0/env-vars/#example-configuration-of-environment-variables
            echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn install --immutable --immutable-cache --check-cache
      - run:
          name: Build packages
          # command: NODE_OPTIONS=--max_old_space_size=8192 yarn build
          command: |
            cd packages/icons
            yarn build
            cd ../icons-vue
            yarn build


      # - run:
      # name: Run Continuous Integration checks
      # command: |
      # yarn ci-check
      # yarn lerna run ci-check

workflows:
  version: 2
  main:
    jobs:
      - system
