version: 2
jobs:
  components:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
            export PATH=$HOME/.yarn/bin:$PATH
      - run:
          name: Install dependencies
          command: yarn install --offline --frozen-lockfile
      - run:
          name: Run Continuous Integration checks
          command: yarn lerna run ci-check --scope carbon-components

workflows:
  version: 2
  main:
    jobs:
      - components
