name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Run Continuous Integration checks
        run: |
          yarn ci-check
          yarn lerna run ci-check
