name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.17'
      - name: Run yarn dedupe
        run: yarn dedupe --check

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: yarn install
      - name: Check formatting of project files
        run: yarn format:diff

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: yarn install
      - name: Lint JavaScript files
        run: yarn lint
      - name: Lint Sass files
        run: yarn lint:styles
