name: Sync generated files
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Sync project dependency files
        run: yarn sync
      - name: Push generated artifacts to GitHub
        env:
          NPM_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Our git status is not clean. Checking in the following files:";
            echo "$(git status --porcelain)";
            git config --global credential.helper 'cache --timeout=120'
            git config --global user.email "carbon@us.ibm.com"
            git config --global user.name "carbon-bot"
            git add -A
            git commit -m "chore(project): sync generated files [skip ci]"
            # Pipe to /dev/null to prevent any token leaks in CI output
            git push -q \
              https://${GH_BOT_TOKEN}:@github.com/carbon-design-system/carbon.git \
              master \
              > /dev/null 2>&1
          fi
